ProductionBackUp/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Amdocs_Account_ID__c</fullName>
        <externalId>true</externalId>
        <label>Amdocs Account ID</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ProductionBackUp/src/objects/LIC__c.object
<CustomObject>
    <fields>
        <fullName>LICNewProposalExistingCustomer__c</fullName>
        <label>LICNewProposalExistingCustomer</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LIC_Proposal_Tracking__c</fullName>
        <defaultValue>&apos;Pradeep&apos;</defaultValue>
        <label>LIC Proposal Tracking</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LIC_Request__c</fullName>
        <defaultValue>&apos;Pradeep&apos;</defaultValue>
        <label>LIC Request</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Proposal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Proposal</label>
        <referenceTo>Proposal__c</referenceTo>
        <relationshipLabel>LICs</relationshipLabel>
        <relationshipName>LICs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>LIC</label>
    <nameField>
        <label>LIC Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LICs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ProductionBackUp/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Identifying_Characteristic__c</fullName>
        <label>Identifying Characteristic</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Of_Interest__c</fullName>
        <label>Product of Interest</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ethernet</fullName>
                </value>
                <value>
                    <fullName>Advanced Voice - Trunking</fullName>
                </value>
                <value>
                    <fullName>Advanced Voice - SIP</fullName>
                </value>
                <value>
                    <fullName>Business Voice Edge</fullName>
                </value>
                <value>
                    <fullName>Business Internet</fullName>
                </value>
                <value>
                    <fullName>Business Television - Public View</fullName>
                </value>
                <value>
                    <fullName>Business Television - Private View</fullName>
                </value>
                <value>
                    <fullName>Business Voice</fullName>
                </value>
                <value>
                    <fullName>Cloud Solutions</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

ProductionBackUp/src/objects/Proposal__c.object
<CustomObject>
    <description>Proposals are a product or service configuration offered to a customer at a set price, similar to a quote. Proposals are mastered in Amdocs and synced with Salesforce.  Proposals are associated to opportunities.</description>
    <fields>
        <fullName>Amdocs_Account_Id__c</fullName>
        <description>AA: 3/29/17 Created to Capture Amdocs Account Id for Proposal Upsert.</description>
        <externalId>true</externalId>
        <label>Amdocs Account Id</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Proposals and Agreements</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Proposal</label>
    <nameField>
        <label>Proposal/Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProductionBackUp/src/classes/CanvasPraposalTest.cls
/****************************************************************************
*Name           : CanvasPraposalTest 
*Description    : Test Class to Cover CanvasProposalcnt and canvasproposalviewcnt
*
******************************************************************************
* Version       Date          Author                        Description
* ----------------------------------------------------------------------------
* 1.0           07/25/2017    Pradeepkumar  Manegalla       Created.
******************************************************************************/
@isTest
public class CanvasPraposalTest
{
    /** Test with an existing contact **/
     
    static testMethod void TestOppUpdate()
    {
        Account account1 = new Account(Name='Test Account');
        insert account1;
       
        Contact con = new contact(LastName='test',FirstName='Con',AccountId = account1.id);
        insert con;

        
        Opportunity opp1 = new Opportunity(Name='Test Opp1',
            AccountId = account1.Id,
            CloseDate = Date.today(),
            StageName='Proposal',
            Product_Of_Interest__c='Ethernet',
            Identifying_Characteristic__c='TestIC'          
        );
        insert opp1;
        
        OpportunityContactRole ocr = new OpportunityContactRole();
        ocr.ContactId = con.Id;
        ocr.OpportunityId = opp1.Id;
        ocr.IsPrimary = TRUE;
        ocr.Role = 'Decision Maker';
        insert ocr;
        
        Proposal__c prpRec = new Proposal__c();
        prpRec.Opportunity__c = opp1.Id;
        prpRec.Name = ''+opp1.Id;
        insert prpRec;
        
      
        
        LIC__c LicRec = new LIC__c(Name='Test Lic',LIC_Request__c='.V1LICNewProposalRequest',Proposal__c = prpRec.Id,
        LIC_Proposal_Tracking__c='Proposal Tracking',LICNewProposalExistingCustomer__c='NewProposalExistingCustomer');
        insert LicRec;
        List<LIC__c> lscLst = new List<LIC__c>();
        lscLst.add(LicRec);
        CanvasPraposalCnt.getOpportunityRecs(opp1,lscLst);
        CanvasPraposalCnt.getOpportunityLst(opp1.Id);
        CanvasPraposalCnt.getProposalRecs(prpRec.Id);
        
       account1.Amdocs_Account_Id__c = '123Test';
       update account1;
       
       CanvasPraposalCnt.getOpportunityLst(opp1.Id);
       //CanvasPraposalCnt.getOpportunityRecs();
    }
    
}