ProductionBackUp/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Identifying_Characteristic__c</fullName>
        <label>Identifying Characteristic</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Of_Interest__c</fullName>
        <label>Product of Interest</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ethernet</fullName>
                </value>
                <value>
                    <fullName>Advanced Voice - Trunking</fullName>
                </value>
                <value>
                    <fullName>Advanced Voice - SIP</fullName>
                </value>
                <value>
                    <fullName>Business Voice Edge</fullName>
                </value>
                <value>
                    <fullName>Business Internet</fullName>
                </value>
                <value>
                    <fullName>Business Television - Public View</fullName>
                </value>
                <value>
                    <fullName>Business Television - Private View</fullName>
                </value>
                <value>
                    <fullName>Business Voice</fullName>
                </value>
                <value>
                    <fullName>Cloud Solutions</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

ProductionBackUp/src/objects/Proposal__c.object
<CustomObject>
    <description>Proposals are a product or service configuration offered to a customer at a set price, similar to a quote. Proposals are mastered in Amdocs and synced with Salesforce.  Proposals are associated to opportunities.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Proposals and Agreements</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>PendingInternalApprovalRules</fullName>
                </value>
                <value>
                    <fullName>InternalApprovalRulesCompleted</fullName>
                </value>
                <value>
                    <fullName>PendingInternalApproval</fullName>
                </value>
                <value>
                    <fullName>ApprovedInternally</fullName>
                </value>
                <value>
                    <fullName>RejectedInternally</fullName>
                </value>
                <value>
                    <fullName>SendToCustomer</fullName>
                </value>
                <value>
                    <fullName>Signed</fullName>
                </value>
                <value>
                    <fullName>RejectedByCustomer</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Proposal</label>
    <nameField>
        <label>Proposal/Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProductionBackUp/src/classes/ProposalTriggerHandlerTest.cls
/****************************************************************************
*Name           : ProposalTriggerHandlerTest
*Description    : Test Class to Cover ProposalTriggerHandler and ProposalTrg
*
******************************************************************************
* Version       Date          Author                Description
* ----------------------------------------------------------------------------
* 1.0           03/31/2017   Kumar manegalla          Created.
 
******************************************************************************/
@isTest
public class ProposalTriggerHandlerTest{
  
    /* Test method to cover ProposalTrg and ProposalTriggerHandler */
    public static testMethod void ProposalTriggertestMethod()
    {
        Test.startTest();
        Account account1 = new Account(Name='Test Account');
        insert account1;
        
        Opportunity opp1 = new Opportunity(Name='Test Opp1',
        AccountId = account1.Id,
        CloseDate = Date.today(),
        StageName='Proposal',
        Product_Of_Interest__c='Ethernet',
        Identifying_Characteristic__c='TestIC'          
        );
        insert opp1;
        
        Proposal__c prpRec = new Proposal__c();
        prpRec.Opportunity__c = opp1.Id;
        prpRec.Status__c = 'Signed';
        prpRec.Name = ''+opp1.Id;
        insert prpRec; 
        update prpRec;
        prpRec.Status__c = 'Sent to customer';
        update prpRec;
        Test.stopTest();
    }
}