ProductionBackUp/src/objects/Proposal__c.object
<CustomObject>
    <description>Proposals are a product or service configuration offered to a customer at a set price, similar to a quote. Proposals are mastered in Amdocs and synced with Salesforce.  Proposals are associated to opportunities.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Proposals and Agreements</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>PendingInternalApprovalRules</fullName>
                </value>
                <value>
                    <fullName>InternalApprovalRulesCompleted</fullName>
                </value>
                <value>
                    <fullName>PendingInternalApproval</fullName>
                </value>
                <value>
                    <fullName>ApprovedInternally</fullName>
                </value>
                <value>
                    <fullName>RejectedInternally</fullName>
                </value>
                <value>
                    <fullName>SendToCustomer</fullName>
                </value>
                <value>
                    <fullName>Signed</fullName>
                </value>
                <value>
                    <fullName>RejectedByCustomer</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Proposal</label>
    <nameField>
        <label>Proposal/Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProductionBackUp/src/classes/ProposalTriggerHandler.cls
/**
*  Description: Proposal Trigger . 
*
*   Modification Log : 
---------------------------------------------------------------------------
    Developer               Date                Description
---------------------------------------------------------------------------
    KUMAR               06/27/2017          Created
******************************************************************************************/
public without sharing class ProposalTriggerHandler
{
    /**
    * Description:
    *
    */
    public void afterUpdate(List<Proposal__c> Proposals)
    {
        try
        {             
            //set<String> oppIdset = new set<String>();
            
            Map<Id,string> oppMap = new Map<Id,string>();
            
            for(Proposal__c propIterate : Proposals)
            {
                if((propIterate.Status__c == 'Signed' || propIterate.Status__c == 'Sent to customer') && propIterate.Opportunity__c != null)
                {
                    //oppIdset.add(propIterate.Opportunity__c);
                    oppMap.put(propIterate.Opportunity__c,propIterate.Status__c);
                }
            }

            List<Opportunity> opportunityList = [SELECT id,Probability,StageName FROM Opportunity WHERE id IN: oppMap.keyset()];
            
            List<Opportunity> opportunityUpdate = new List<Opportunity>();
            for(Opportunity oppIterate : opportunityList )
            {
                if(oppMap.containsKey(oppIterate.Id))
                {
                    if(oppMap.get(oppIterate.Id) == 'Signed')
                    {
                        oppIterate.StageName= 'Closed Won';
                        oppIterate.Probability = 100;
                    }
                    else if(oppMap.get(oppIterate.Id) == 'Sent to customer')
                    {
                        oppIterate.StageName= 'Negotiation';
                        oppIterate.Probability= 90;
                    }
                    opportunityUpdate.add(oppIterate);
                }
            }
            
            if(!opportunityUpdate.isEmpty())
                update opportunityUpdate ;  
            
            system.debug('Optys - '+opportunityUpdate); 
        }catch(Exception e)
        {
        
        }

    }
}